"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    var inserts = `INSERT INTO "Dogs" (id, "name", breed, gender, age, description, picture, "createdAt", "updatedAt") VALUES(1, 'Luna', 'Bloodhound Mix', 'Female', '2019-05-18 00:00:00.000', 'Luna is a calm puppy with a very easy-going temperament, just like her dad who is a purebred Bloodhound. She LOVES to swim! She''s great with dogs of all ages but intros must be slow since she is only used to her mom and her siblings. Because of this, she can run from strange dogs at first. As she''s such a young pup she will need house training, proper socialization, puppy classes and lots of love. Local adopters are given preference as we will not send young puppies very far away. We prefer stay-at-home or work-from-home adopters. Please apply with the link below and we will be in touch for private showings if your application matches our criteria. We follow a holistic protocol which is healthier for the pups. First vaccines were given but vaccines do not guarantee immunity so they must be kept at home for at least two weeks subsequent to vaccines, as each vaccine suppresses the immune system. All pups are sent home with 30 days free Trupanion pet insurance.', '5398-Luna-14.jpg', '2019-08-12 00:00:00.000', '2019-08-12 00:00:00.000');
    INSERT INTO "Dogs" (id, "name", breed, gender, age, description, picture, "createdAt", "updatedAt") VALUES(2, 'Lexi', 'Bloodhound Mix', 'Female', '2019-05-18 00:00:00.000', 'Lexi is a Bloodhound Mix. These Bloodhound mix pups will need house training, proper socialization, puppy classes and lots of love. Local adopters are given preference as we will not send young puppies very far away. We prefer stay-at-home or work-from-home adopters. Please follow link below to apply and we will be in touch for private showings if your application matches our criteria. You must have an application on file. We follow a holistic protocol which is healthier for the pups. First vaccines already given, but vaccines do not guarantee immunity so they must keep at home for at least two weeks subsequent to vaccines, as each vaccine suppresses the immune system. All pups are sent home with 30 days free Trupanion pet insurance.', '5404-Lexi-18.jpg', '2019-08-12 00:00:00.000', '2019-08-12 00:00:00.000');
    INSERT INTO "Dogs" (id, "name", breed, gender, age, description, picture, "createdAt", "updatedAt") VALUES(3, 'Milo', 'Great Pyr / Retriever Mix', 'Male', '2018-02-01 00:00:00.000', 'Milo is a 2.5-year-old friendly Great Pyr mix who loves everyone. He was fostered with 3 big Labs and is great with everyone. He''s affectionate, goofy, and outgoing. Never an accident in the house. Likes to chew on marrow bones/bully sticks, get chin and ear rubs, play with rope toys, relax on the couch and meet new people. Milo would not do well in a home with cats or small dogs. Available 8/6/19. Follow link below to apply for the fastest response. We''re not always able to take phone calls during the day as we''re a small shelter with a volunteer-based staff.', '5423-Milo1.jpg', '2019-08-12 00:00:00.000', '2019-08-12 00:00:00.000');
    INSERT INTO "Dogs" (id, "name", breed, gender, age, description, picture, "createdAt", "updatedAt") VALUES(4, 'Holly', 'Lab / Pointer / Beagle Mix', 'Female', '2019-02-14 00:00:00.000', 'Holly is an adorable pup who is house trained and crate trained, and already knows some basic obedience commands. She is just a perfect pup for a family. Like any puppy she has puppy energy so would be great for a family or adopter who will play with her. Another playful dog would be ideal for her. Holly is a good pup. She will lie by your side and entertain herself while you''re on your computer. Her adoptive family worked with her and trained her but returned her due to unforeseen circumstances. Holly and her sisters Summer and Suzi came up from TX as bottle-fed pups. She is already spayed and has received her puppy shots and is microchipped. Follow the link to apply below!', '5370-Holly-9.jpg', '2019-08-12 00:00:00.000', '2019-08-12 00:00:00.000');
    INSERT INTO "Dogs" (id, "name", breed, gender, age, description, picture, "createdAt", "updatedAt") VALUES(5, 'Charity', 'Boxer / Bully / Lab Mix', 'Female', '2018-08-01 00:00:00.000', 'Charity is just a year old and she has so much to offer. She is very affectionate and will lean into you. She was a recent return and we''re a bit baffled, as her adopters wanted her to be able to go off-leash and she just wasn''t ready. This is not unusual as very few adolescent dogs are ready to go off leash. One-year old dogs are still puppies so this little love bug (who lives up to her name) is looking for her forever home. She''s just a blast, loves other dogs, loves to go into the doggy pool, and she will play fetch. She would do best with a fenced in yard because she can pull on leash when she''s excited. Please follow link below to apply!', '5421-Charity-12.jpg', '2019-08-12 00:00:00.000', '2019-08-12 00:00:00.000');
    INSERT INTO "Dogs" (id, "name", breed, gender, age, description, picture, "createdAt", "updatedAt") VALUES(6, 'Amber', 'Bloodhound Mix', 'Female', '2019-01-01 00:00:00.000', 'Amber is part of a litter of Bloodhound pups whose dad is Clyde, a purebred Bloodhound we recently placed. Mom looks like a Lab mix. She would a make great family pet and perhaps a great search and rescue dog once grown. She is a sweetheart and very affectionate and would do best with another dog in the house to build her confidence and make her feel more secure. Amber is in a foster home and can be met by private appointment after we receive your application. Please follow the link below to apply!', '5367-Amber-14.jpg', '2019-08-12 00:00:00.000', '2019-08-12 00:00:00.000');
    INSERT INTO "Dogs" (id, "name", breed, gender, age, description, picture, "createdAt", "updatedAt") VALUES(7, 'Itsy', 'Jack Russell Terrier', 'Female', '2007-01-01 00:00:00.000', 'Hi, my name is Itsy and I''m a Jack Russell. I''m 12+ years old and weigh ~18 pounds. I''m pretty laid back for a Jack. I get along fine with other dogs and cats. I''m looking for a place to live out my years. I have a heart murmur and some mammary growths so I may not be a candidate for surgery. Despite my health issues, I''m a happy little dog looking for a warm bed and a nice lap. Maybe a senior would consider me? ', '5417-Itsy-13.jpg', '2019-08-12 00:00:00.000', '2019-08-12 00:00:00.000');
    INSERT INTO "Dogs" (id, "name", breed, gender, age, description, picture, "createdAt", "updatedAt") VALUES(8, 'Chance', 'Collie / Husky Mix', 'Male', '2018-11-01 00:00:00.000', 'Meet Chance, a sweet, affectionate, active Collie/Husky mix who is awaiting his forever home. Chance is a big lover boy who craves affection and snuggles. He is house broken, neutered, and well trained - he knows the commands ''touch'', ''watch'', ''sit'', ''down'' and ''come''. He has great recall and loves to go for long walks/runs with anyone who will go with him. He loves other dogs. He gets bored easily, so he would do best if he was able to spend most of the day playing/exercising or given direction in a positive way. He will do better in a home with older children, or no children at all, even though he loves kids and is very good natured. However, he doesn''t know his own strength, and can scratch them and knock them down. He should be in a home where there are no small animals. Other dogs are great, but he chases cats and chickens and doesn''t know when to stop. He can be timid with men, but he warms up very quickly.', '5410-Chance-16.jpg', '2019-08-12 00:00:00.000', '2019-08-12 00:00:00.000');
    INSERT INTO "Dogs" (id, "name", breed, gender, age, description, picture, "createdAt", "updatedAt") VALUES(9, 'Bobby', 'Chi-weenie Mix', 'Male', '2019-08-01 00:00:00.000', 'Hi, my name is Bobby and I''m a two year old Chi-weenie. I was adopted last year but after a year my family realized that I''m best in a home without small children. I got nervous with the toddler''s shrieking noises and I developed sensitivities, so a quiet home would be a relief for me. Also, if I''m sound asleep I don''t like to be touched or picked up. I developed some anxiety over that, and Save A Dog says lashing out is my coping mechanism and is not my fault. Other than those two things, I''m a fun little guy. I love to spin around with a new toy. I love to cuddle up under a blanket. I''m house trained but if you leave me home for hours, well, a dog''s gotta do what a dog''s gotta do. I can only hold it for so long. How about an adult home where someone works part time or is home during the day? I''m not for inexperienced dog owners, so please have a little experience. Us little guys have our quirks but just remember, it''s a big world out there and I''m really small, under 20 lbs. I should be available to meet once you submit your application. I''ll be in a foster home until my new forever person finds me.', '5411-Bobby-20.jpg', '2019-08-12 00:00:00.000', '2019-08-12 00:00:00.000');
    INSERT INTO "Dogs" (id, "name", breed, gender, age, description, picture, "createdAt", "updatedAt") VALUES(10, 'Evangeline', 'Lab / Shepherd / Hound Mix', 'Female', '2019-04-01 00:00:00.000', 'Evangeline is a pup who LOVES the POOL. She will lie in it like it''s a hot tub. She loves to play with the big dogs and might be too rough for smaller dogs. She is super submissive, belly up when she first meets you. She is gentle with toddlers, timid with men. She came to us with her siblings, Bayou and Creole, from a rescue in Louisiana. She is 90% on her house training and with a part time worker she will get proper socialization and training. She is a LOVE and is ready to give her all to you if you just invest a little time and training. She needs another dog in the family to build confidence. Please follow the link below to apply.', '5348-Evangeline-18.jpg', '2019-08-12 00:00:00.000', '2019-08-12 00:00:00.000');`.split(
      "/n"
    );

    for (let i = 0; i < inserts.length; i++) {
      await queryInterface.sequelize.query(inserts[i]);
    }
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('People', null, {});
    */
  }
};
